### DISCUSSION TITLE
Is there any way to install extensions from the CLI ?

### DISCUSSION THREAD

**Discussion by haysberg** [mjakeman/extension-manager#194] [Q&A] [answered]
Hello everyone,

I've got a fairly simple Fedora setup script as I often have to reinstall my machine.
I was wondering if there was an option to install a specific extension from the command line.

Something like `flatpak run com.mattjakeman.ExtensionManager install extension.name` ?

Thanks for such an amazing project, I hope that it will continue to grow !

**Comment by mjakeman** [comment, marked as answer]
Hi, thanks for the interest!

There's nothing like that implemented at the moment, although there's a tracking issue for it (#172). I'm also planning on adding a 'Lists' feature which will let you "share" extensions between computers - this is tracked in #75.

Something important to note is that GNOME Shell handles the actual extension installation, and we simply send it a request. As part of this, it requires the user to click "Install" on a popup which is not something we can control. So any CLI interface would still have to respect this limitation, meaning true hands-free installation is not really possible. The lists feature should definitely make this easier though.

**Comment by schuerg** [comment]
Perhaps a viable solution could also be to allow export/import of a list of currently installed extensions in a common text format. Or even better, define a filesystem directory containing plaintext metadata about extensions to be installed. The files in this directory could be versioned with a VCS like git.

```yaml
# ${XDG_CONFIG_HOME}/extension-manager/extensions.yaml
# ~/.config/extension-manager/extensions.yaml

user-extensions:
  - id: launch-new-instance@gnome-shell-extensions.gcampax.github.com
  - id: places-menu@gnome-shell-extensions.gcampax.github.com
    shell-version: 42
  - id: window-list@gnome-shell-extensions.gcampax.github.com
```
